Restore deployment

diff --git a/.github/workflows/deploy-zeit-staging.yml b/.github/workflows/deploy-zeit-staging.yml
--- a/.github/workflows/deploy-zeit-staging.yml
+++ b/.github/workflows/deploy-zeit-staging.yml
@@ -53,44 +53,87 @@ jobs:
         # XXX You can use https://jqplay.org/ if you want to play around with "jq" to manipulate JSON
         run: |
           # Print the version of the "now" CLI being used (helps debugging)
-          now --version
+           now --version
 
-          # Resolving customer to deploy based on the github event input, when using manual deployment triggerer through "workflow_dispatch" event
-          # Falls back to the customer specified in the now.json file, which is most useful when deployment is triggered through "push" event
-          MANUAL_TRIGGER_CUSTOMER="${{ github.event.inputs.customer}}"
-          echo "MANUAL_TRIGGER_CUSTOMER: " $MANUAL_TRIGGER_CUSTOMER
-          echo "MANUAL_TRIGGER_CUSTOMER=$MANUAL_TRIGGER_CUSTOMER" >> $GITHUB_ENV
+           # Resolving customer to deploy based on the github event input, when using manual deployment triggerer through "workflow_dispatch" event
+           # Falls back to the customer specified in the now.json file, which is most useful when deployment is triggered through "push" event
+           MANUAL_TRIGGER_CUSTOMER="${{ github.event.inputs.customer}}"
+           echo "MANUAL_TRIGGER_CUSTOMER: " $MANUAL_TRIGGER_CUSTOMER
+           echo "MANUAL_TRIGGER_CUSTOMER=$MANUAL_TRIGGER_CUSTOMER" >> $GITHUB_ENV
 
-          CUSTOMER_REF_TO_DEPLOY="${MANUAL_TRIGGER_CUSTOMER:-$(cat now.json | jq --raw-output '.build.env.NEXT_PUBLIC_CUSTOMER_REF')}"
-          echo "Customer to deploy: " $CUSTOMER_REF_TO_DEPLOY
-          echo "CUSTOMER_REF_TO_DEPLOY=$CUSTOMER_REF_TO_DEPLOY" >> $GITHUB_ENV
+           CUSTOMER_REF_TO_DEPLOY="${MANUAL_TRIGGER_CUSTOMER:-$(cat now.json | jq --raw-output '.build.env.NEXT_PUBLIC_CUSTOMER_REF')}"
+           echo "Customer to deploy: " $CUSTOMER_REF_TO_DEPLOY
+           echo "CUSTOMER_REF_TO_DEPLOY=$CUSTOMER_REF_TO_DEPLOY" >> $GITHUB_ENV
 
-          # Apply all aliases specified in the now.json file (if any is specified)
-          # Find all aliases configured in the customer deployment configuration file (now.json)
-          ZEIT_DEPLOYMENT_ALIASES_JSON=$(cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.alias')
-          echo "Custom aliases: " $ZEIT_DEPLOYMENT_ALIASES_JSON
+           # Deploy the customer on Vercel using the customer ref (e.g: "yarn deploy:customer1")
+           # Store the output in a variable so we can extract metadata from it
+           ZEIT_DEPLOYMENT_OUTPUT=`yarn deploy:$CUSTOMER_REF_TO_DEPLOY --token $ZEIT_TOKEN`
 
-          # Convert the JSON array into a bash array - See https://unix.stackexchange.com/a/615717/60329
-          readarray -t ZEIT_DEPLOYMENT_ALIASES < <(jq --raw-output '.alias[]' < now.$CUSTOMER_REF_TO_DEPLOY.staging.json)
+           # Extract the Vercel deployment url from the deployment output
+           ZEIT_DEPLOYMENT_URL=`echo $ZEIT_DEPLOYMENT_OUTPUT | egrep -o 'https?://[^ ]+.vercel.app'`
+           echo "Deployment url: " $ZEIT_DEPLOYMENT_URL
+           echo "ZEIT_DEPLOYMENT_URL=$ZEIT_DEPLOYMENT_URL" >> $GITHUB_ENV
 
-          # Count the number of element in the array, will be 0 if it's an empty array, or if the "alias" key wasn't defined
-          ZEIT_DEPLOYMENT_ALIASES_COUNT=${#ZEIT_DEPLOYMENT_ALIASES[@]}
+           # Build the alias domain based on our own rules (NRN own rules)
+           # Basically, if a branch starts with "v[0-9]" then we consider it to be a "preset branch" and we use the branch name as alias (e.g: "v2-mst-xxx")
+           # Otherwise, we use the deployment name and suffix it using the branch name (e.g: "v2-mst-xxx-branch-name")
+           if [[ ${CURRENT_BRANCH##*/} =~ ^v[0-9]{1,}- ]]; then # Checking if pattern matches with "vX-" where X is a number
+             ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=${CURRENT_BRANCH##*/}
+           else
+             ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=$(cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.name')-${CURRENT_BRANCH##*/}
+           fi
+           echo "Resolved domain alias: " $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
 
-          # Check if there are no aliases configured
-          if [ "$ZEIT_DEPLOYMENT_ALIASES" > 0 ]
-          then
-            echo "$ZEIT_DEPLOYMENT_ALIASES_COUNT alias(es) found. Aliasing them now..."
+           # Zeit alias only allows 41 characters in the domain name, so we only keep the first 41 (41 = 53 - 11 - 1) characters (because Zeit needs 7 chars for ".vercel.app" at the end of the domain name, and count starts at 1, not 0)
+           # Also, in order to remove forbidden characters, we transform every characters which are not a "alnum" and \n or \r into '-'
+           ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=$(echo $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS | head -c 41 | tr -c '[:alnum:]\r\n' - | tr '[:upper:]' '[:lower:]')
+           echo "Sanitized domain alias (1): " $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
 
-            # For each alias configured, then assign it to the deployed domain
-            for DEPLOYMENT_ALIAS in "${ZEIT_DEPLOYMENT_ALIASES[@]}"; do
-              echo "npx now alias "$ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS
-              npx now alias $ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed for '$DEPLOYMENT_ALIAS', but the build will continue regardless."
-            done
-          else
-            # $ZEIT_DEPLOYMENT_ALIASES is null, this happens when it was not defined in the now.json file
-            echo "There are no more aliases to configure. You can add more aliases from your now.json 'alias' property. See https://vercel.com/docs/configuration?query=alias%20domain#project/alias"
-            echo "$ZEIT_DEPLOYMENT_ALIASES"
-          fi
+           # Recursively remove any trailing dash ('-') to protect against invalid alias domain (not allowed to end with a trailing slash)
+           while [[ "$ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS" == *- ]]
+           do
+             ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=${ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS::-1}
+           done
+           echo "Sanitized domain alias (2): " $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
+
+           # Build alias url
+           ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS="${ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS}.vercel.app"
+           echo "ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=$ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS" >> $GITHUB_ENV
+           echo "Alias domain: "$ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
+           echo "Aliasing the deployment using the git branch alias:"
+           echo "npx now alias "$ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
+
+           # Create Vercel alias, use "||" to allow failure (keep the build going) even if the alias fails
+           ZEIT_ALIASING_OUTPUT=`npx now alias $ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed for '$ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS', but the build will continue regardless."`
+           echo $ZEIT_ALIASING_OUTPUT
+           # TODO Resolve whether the aliasing has worked and change the GitHub comment "Comment PR (Deployment success)"
+
+           # Apply all aliases specified in the now.json file (if any is specified)
+           # Find all aliases configured in the customer deployment configuration file (now.json)
+           ZEIT_DEPLOYMENT_ALIASES_JSON=$(cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.alias')
+           echo "Custom aliases: " $ZEIT_DEPLOYMENT_ALIASES_JSON
+
+           # Convert the JSON array into a bash array - See https://unix.stackexchange.com/a/615717/60329
+           readarray -t ZEIT_DEPLOYMENT_ALIASES < <(jq --raw-output '.alias[]' < now.$CUSTOMER_REF_TO_DEPLOY.staging.json)
+
+           # Count the number of element in the array, will be 0 if it's an empty array, or if the "alias" key wasn't defined
+           ZEIT_DEPLOYMENT_ALIASES_COUNT=${#ZEIT_DEPLOYMENT_ALIASES[@]}
+
+           # Check if there are no aliases configured
+           if [ "$ZEIT_DEPLOYMENT_ALIASES" > 0 ]
+           then
+             echo "$ZEIT_DEPLOYMENT_ALIASES_COUNT alias(es) found. Aliasing them now..."
+
+             # For each alias configured, then assign it to the deployed domain
+             for DEPLOYMENT_ALIAS in "${ZEIT_DEPLOYMENT_ALIASES[@]}"; do
+               echo "npx now alias "$ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS
+               npx now alias $ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed for '$DEPLOYMENT_ALIAS', but the build will continue regardless."
+             done
+           else
+             # $ZEIT_DEPLOYMENT_ALIASES is null, this happens when it was not defined in the now.json file
+             echo "There are no more aliases to configure. You can add more aliases from your now.json 'alias' property. See https://vercel.com/docs/configuration?query=alias%20domain#project/alias"
+             echo "$ZEIT_DEPLOYMENT_ALIASES"
+           fi
         env:
           ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }} # Passing github's secret to the worker
           CURRENT_BRANCH: ${{ github.ref }} # Passing current branch to the worker
