Migrate "now" to "vercel" (#210) (modified)

diff --git a/.github/workflows/deploy-zeit-staging.yml b/.github/workflows/deploy-zeit-staging.yml
--- a/.github/workflows/deploy-zeit-staging.yml
+++ b/.github/workflows/deploy-zeit-staging.yml
@@ -35,7 +35,7 @@ jobs:
           node-version: '12.x' # Use the same node.js version as the one Zeit's uses (currently node12.x)
 
   # Starts a Zeit deployment, using the staging configuration file of the default institution
-  # The default institution is the one defined in the `now.json` file (which is a symlink to the actual file)
+  # The default institution is the one defined in the `vercel.json` file (which is a symlink to the actual file)
   # N.B: It's Zeit that will perform the actual deployment
   start-staging-deployment:
     name: Starts Zeit deployment (staging) (Ubuntu 18.04)
@@ -45,23 +45,23 @@ jobs:
       - uses: actions/checkout@v1 # Get last commit pushed - XXX See https://github.com/actions/checkout
       - name: Deploying on Zeit (staging)
         # Workflow overview:
-        #   - Resolve customer to deploy from github event input (falls back to resolving it from now.json file)
+        #   - Resolve customer to deploy from github event input (falls back to resolving it from vercel.json file)
         #   - Resolve $ZEIT_DEPLOYMENT_URL
         #   - Get stdout from deploy command (stderr prints build steps and stdout prints deployment url, which is what we are really looking for)
         #   - Set the deployment url that will be included in the eventual PR comment
         #   - Create a deployment alias based on the branch name, and link it to the deployment (so that each branch has its own domain automatically aliased to the latest commit)
         # XXX You can use https://jqplay.org/ if you want to play around with "jq" to manipulate JSON
         run: |
-          # Print the version of the "now" CLI being used (helps debugging)
-          now --version
+          # Print the version of the "vercel" CLI being used (helps debugging)
+          vercel --version
 
           # Resolving customer to deploy based on the github event input, when using manual deployment triggerer through "workflow_dispatch" event
-          # Falls back to the customer specified in the now.json file, which is most useful when deployment is triggered through "push" event
+          # Falls back to the customer specified in the vercel.json file, which is most useful when deployment is triggered through "push" event
           MANUAL_TRIGGER_CUSTOMER="${{ github.event.inputs.customer}}"
           echo "MANUAL_TRIGGER_CUSTOMER: " $MANUAL_TRIGGER_CUSTOMER
           echo "MANUAL_TRIGGER_CUSTOMER=$MANUAL_TRIGGER_CUSTOMER" >> $GITHUB_ENV
 
-          CUSTOMER_REF_TO_DEPLOY="${MANUAL_TRIGGER_CUSTOMER:-$(cat now.json | jq --raw-output '.build.env.NEXT_PUBLIC_CUSTOMER_REF')}"
+          CUSTOMER_REF_TO_DEPLOY="${MANUAL_TRIGGER_CUSTOMER:-$(cat vercel.json | jq --raw-output '.build.env.NEXT_PUBLIC_CUSTOMER_REF')}"
           echo "Customer to deploy: " $CUSTOMER_REF_TO_DEPLOY
           echo "CUSTOMER_REF_TO_DEPLOY=$CUSTOMER_REF_TO_DEPLOY" >> $GITHUB_ENV
 
@@ -80,7 +80,7 @@ jobs:
           if [[ ${CURRENT_BRANCH##*/} =~ ^v[0-9]{1,}- ]]; then # Checking if pattern matches with "vX-" where X is a number
             ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=${CURRENT_BRANCH##*/}
           else
-            ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=$(cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.name')-${CURRENT_BRANCH##*/}
+            ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=$(cat vercel.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.name')-${CURRENT_BRANCH##*/}
           fi
           echo "Resolved domain alias: " $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
 
@@ -101,19 +101,19 @@ jobs:
           echo "ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS=$ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS" >> $GITHUB_ENV
           echo "Alias domain: "$ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
           echo "Aliasing the deployment using the git branch alias:"
-          echo "npx now alias "$ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
+          echo "npx vercel alias "$ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS
 
           # Create Vercel alias, use "||" to allow failure (keep the build going) even if the alias fails
-          ZEIT_ALIASING_OUTPUT=`npx now alias $ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed for '$ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS', but the build will continue regardless."`
+          ZEIT_ALIASING_OUTPUT=`npx vercel alias $ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed for '$ZEIT_DEPLOYMENT_AUTO_BRANCH_ALIAS', but the build will continue regardless."`
           echo $ZEIT_ALIASING_OUTPUT
           # TODO Resolve whether the aliasing has worked and change the GitHub comment "Comment PR (Deployment success)"
 
-          # Find all custom aliases configured in the customer deployment configuration file (now.json)
-          ZEIT_DEPLOYMENT_ALIASES_JSON=$(cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.alias')
+          # Find all custom aliases configured in the customer deployment configuration file (vercel.json)
+          ZEIT_DEPLOYMENT_ALIASES_JSON=$(cat vercel.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.alias')
           echo "Custom aliases: " $ZEIT_DEPLOYMENT_ALIASES_JSON
 
           # Convert the JSON array into a bash array - See https://unix.stackexchange.com/a/615717/60329
-          readarray -t ZEIT_DEPLOYMENT_ALIASES < <(jq --raw-output '.alias[]' < now.$CUSTOMER_REF_TO_DEPLOY.staging.json)
+          readarray -t ZEIT_DEPLOYMENT_ALIASES < <(jq --raw-output '.alias[]' < vercel.$CUSTOMER_REF_TO_DEPLOY.staging.json)
 
           # Count the number of element in the array, will be 0 if it's an empty array, or if the "alias" key wasn't defined
           ZEIT_DEPLOYMENT_ALIASES_COUNT=${#ZEIT_DEPLOYMENT_ALIASES[@]}
@@ -125,12 +125,12 @@ jobs:
 
             # For each alias configured, then assign it to the deployed domain
             for DEPLOYMENT_ALIAS in "${ZEIT_DEPLOYMENT_ALIASES[@]}"; do
-              echo "npx now alias "$ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS
-              npx now alias $ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed for '$DEPLOYMENT_ALIAS', but the build will continue regardless."
+              echo "npx vercel alias "$ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS
+              npx vercel alias $ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed for '$DEPLOYMENT_ALIAS', but the build will continue regardless."
             done
           else
-            # $ZEIT_DEPLOYMENT_ALIASES is null, this happens when it was not defined in the now.json file
-            echo "There are no more aliases to configure. You can add more aliases from your now.json 'alias' property. See https://vercel.com/docs/configuration?query=alias%20domain#project/alias"
+            # $ZEIT_DEPLOYMENT_ALIASES is null, this happens when it was not defined in the vercel.json file
+            echo "There are no more aliases to configure. You can add more aliases from your vercel.json 'alias' property. See https://vercel.com/docs/configuration?query=alias%20domain#project/alias"
             echo "$ZEIT_DEPLOYMENT_ALIASES"
           fi
         env:
@@ -181,9 +181,9 @@ jobs:
       - uses: actions/checkout@v1 # Get last commit pushed - XXX See https://github.com/actions/checkout
       - name: Resolving deployment url from Zeit
         # Workflow overview:
-        #   - Resolve customer to deploy from github event input (falls back to resolving it from now.json file)
+        #   - Resolve customer to deploy from github event input (falls back to resolving it from vercel.json file)
         #   - Resolve $ZEIT_DEPLOYMENT_URL
-        #     - Fetch all deployments data (by using the scope in `now.json`)
+        #     - Fetch all deployments data (by using the scope in `vercel.json`)
         #     - Resolve the last url (from `response.deployments[0].url`)
         #     - Remove the `"` character to pre-format url
         # We need to set env the url for next step, formatted as `https://${$ZEIT_DEPLOYMENT}`
@@ -195,17 +195,17 @@ jobs:
           echo "MANUAL_TRIGGER_CUSTOMER: " $MANUAL_TRIGGER_CUSTOMER
           echo "MANUAL_TRIGGER_CUSTOMER=$MANUAL_TRIGGER_CUSTOMER" >> $GITHUB_ENV
 
-          CUSTOMER_REF_TO_DEPLOY="${MANUAL_TRIGGER_CUSTOMER:-$(cat now.json | jq --raw-output '.build.env.NEXT_PUBLIC_CUSTOMER_REF')}"
+          CUSTOMER_REF_TO_DEPLOY="${MANUAL_TRIGGER_CUSTOMER:-$(cat vercel.json | jq --raw-output '.build.env.NEXT_PUBLIC_CUSTOMER_REF')}"
           echo "Customer that was deployed: " $CUSTOMER_REF_TO_DEPLOY
           echo "CUSTOMER_REF_TO_DEPLOY=$CUSTOMER_REF_TO_DEPLOY" >> $GITHUB_ENV
 
           # Resolve Vercel team ID
-          VERCEL_TEAM_ID=`cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.scope'`
+          VERCEL_TEAM_ID=`cat vercel.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.scope'`
           echo "Vercel team ID: " $VERCEL_TEAM_ID
           echo "VERCEL_TEAM_ID=$VERCEL_TEAM_ID" >> $GITHUB_ENV
 
           # Resolve Vercel project name
-          VERCEL_PROJECT_NAME=`cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.name'`
+          VERCEL_PROJECT_NAME=`cat vercel.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.name'`
           echo "Vercel project name: " $VERCEL_PROJECT_NAME
           echo "VERCEL_PROJECT_NAME=$VERCEL_PROJECT_NAME" >> $GITHUB_ENV
 
@@ -292,9 +292,9 @@ jobs:
       - uses: actions/checkout@v1 # Get last commit pushed - XXX See https://github.com/actions/checkout
       - name: Resolving deployment url from Zeit
         # Workflow overview:
-        #   - Resolve customer to deploy from github event input (falls back to resolving it from now.json file)
+        #   - Resolve customer to deploy from github event input (falls back to resolving it from vercel.json file)
         #   - Resolve $ZEIT_DEPLOYMENT_URL
-        #     - Fetch all deployments data (by using the scope in `now.json`)
+        #     - Fetch all deployments data (by using the scope in `vercel.json`)
         #     - Resolve the last url (from `response.deployments[0].url`)
         #     - Remove the `"` character to pre-format url
         # We need to set env the url for next step, formatted as `https://${$ZEIT_DEPLOYMENT}/en` using /en endpoint to improve perfs by avoiding the url redirect on /
@@ -306,17 +306,17 @@ jobs:
           echo "MANUAL_TRIGGER_CUSTOMER: " $MANUAL_TRIGGER_CUSTOMER
           echo "MANUAL_TRIGGER_CUSTOMER=$MANUAL_TRIGGER_CUSTOMER" >> $GITHUB_ENV
 
-          CUSTOMER_REF_TO_DEPLOY="${MANUAL_TRIGGER_CUSTOMER:-$(cat now.json | jq --raw-output '.build.env.NEXT_PUBLIC_CUSTOMER_REF')}"
+          CUSTOMER_REF_TO_DEPLOY="${MANUAL_TRIGGER_CUSTOMER:-$(cat vercel.json | jq --raw-output '.build.env.NEXT_PUBLIC_CUSTOMER_REF')}"
           echo "Customer that was deployed: " $CUSTOMER_REF_TO_DEPLOY
           echo "CUSTOMER_REF_TO_DEPLOY=$CUSTOMER_REF_TO_DEPLOY" >> $GITHUB_ENV
 
           # Resolve Vercel team ID
-          VERCEL_TEAM_ID=`cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.scope'`
+          VERCEL_TEAM_ID=`cat vercel.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.scope'`
           echo "Vercel team ID: " $VERCEL_TEAM_ID
           echo "VERCEL_TEAM_ID=$VERCEL_TEAM_ID" >> $GITHUB_ENV
 
           # Resolve Vercel project name
-          VERCEL_PROJECT_NAME=`cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.name'`
+          VERCEL_PROJECT_NAME=`cat vercel.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.name'`
           echo "Vercel project name: " $VERCEL_PROJECT_NAME
           echo "VERCEL_PROJECT_NAME=$VERCEL_PROJECT_NAME" >> $GITHUB_ENV
 
