Add logs for $ZEIT_DEPLOYMENT_ALIAS when deploying + make aliasing not crash the build anymore + change way to define variables sent to $GITHUB_ENV so that they're also set for the rest of the script

diff --git a/.github/workflows/deploy-zeit-staging.yml b/.github/workflows/deploy-zeit-staging.yml
--- a/.github/workflows/deploy-zeit-staging.yml
+++ b/.github/workflows/deploy-zeit-staging.yml
@@ -79,24 +79,31 @@ jobs:
           else
             ZEIT_DEPLOYMENT_ALIAS=$(cat now.$CUSTOMER_TO_DEPLOY.staging.json | jq -r '.name')-${CURRENT_BRANCH##*/}
           fi
+          echo "Resolved domain alias: " $ZEIT_DEPLOYMENT_ALIAS
 
           # Zeit alias only allows 41 characters in the domain name, so we only keep the first 41 (41 = 53 - 11 - 1) characters (because Zeit needs 7 chars for ".vercel.app" at the end of the domain name, and count starts at 1, not 0)
           # Also, in order to remove forbidden characters, we transform every characters which are not a "alnum" and \n or \r into '-'
           ZEIT_DEPLOYMENT_ALIAS=$(echo $ZEIT_DEPLOYMENT_ALIAS | head -c 41 | tr -c '[:alnum:]\r\n' - | tr '[:upper:]' '[:lower:]')
+          echo "Sanitized domain alias (1): " $ZEIT_DEPLOYMENT_ALIAS
 
           # Recursively remove any trailing dash ('-') to protect against invalid alias domain (not allowed to end with a trailing slash)
           while [[ "$ZEIT_DEPLOYMENT_ALIAS" == *- ]]
           do
             ZEIT_DEPLOYMENT_ALIAS=${ZEIT_DEPLOYMENT_ALIAS::-1}
           done
+          echo "Sanitized domain alias (2): " $ZEIT_DEPLOYMENT_ALIAS
 
-          # Build alias url and create Vercel alias
-          ZEIT_DEPLOYMENT_ALIAS=$ZEIT_DEPLOYMENT_ALIAS.vercel.app
-          echo "ZEIT_DEPLOYMENT_ALIAS=https://$ZEIT_DEPLOYMENT_ALIAS" >> $GITHUB_ENV
+          # Build alias url
+          ZEIT_DEPLOYMENT_ALIAS="${ZEIT_DEPLOYMENT_ALIAS}.vercel.app"
+          echo "ZEIT_DEPLOYMENT_ALIAS=$ZEIT_DEPLOYMENT_ALIAS" >> $GITHUB_ENV
           echo "Alias domain: "$ZEIT_DEPLOYMENT_ALIAS
           echo "Aliasing the deployment using the git branch alias:"
           echo "npx now alias "$ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_ALIAS
-          npx now alias $ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_ALIAS --token $ZEIT_TOKEN
+
+          # Create Vercel alias, use "||" to allow failure (keep the build going) even if the alias fails
+          ZEIT_ALIASING_OUTPUT=`npx now alias $ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed, but the build will continue regardless."`
+          echo $ZEIT_ALIASING_OUTPUT
+          # TODO Resolve whether the aliasing has worked and change the GitHub comment "Comment PR (Deployment success)"
         env:
           ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }} # Passing github's secret to the worker
           CURRENT_BRANCH: ${{ github.ref }} # Passing current branch to the worker
@@ -131,7 +138,7 @@ jobs:
           body: |
             :white_check_mark:&nbsp; Deployment **SUCCESS**
             Commit ${{ github.sha }} successfully deployed to [${{ env.ZEIT_DEPLOYMENT_URL }}](${{ env.ZEIT_DEPLOYMENT_URL }})
-            Deployment aliased as ${{ env.ZEIT_DEPLOYMENT_ALIAS }}
+            Deployment aliased as [https://${{ env.ZEIT_DEPLOYMENT_ALIAS }}](${{ env.ZEIT_DEPLOYMENT_ALIAS }})
 
   # Runs E2E tests against the Zeit deployment
   run-2e2-tests:
@@ -179,8 +186,9 @@ jobs:
           # Parse the deployments (as json) to find the latest deployment url, while stripping the double quotes
           # TODO Do not use '.deployments [0].url' blindly, but filter the deployments array first to make sure to consider only the deployments where "name" is equal to $VERCEL_PROJECT_NAME
           ZEIT_DEPLOYMENT=`echo $ALL_ZEIT_DEPLOYMENTS | jq '.deployments [0].url' | tr -d \"`
-          echo "ZEIT_DEPLOYMENT_URL=https://$ZEIT_DEPLOYMENT" >> $GITHUB_ENV
+          ZEIT_DEPLOYMENT_URL="https://$ZEIT_DEPLOYMENT"
           echo "Url where to run E2E tests (ZEIT_DEPLOYMENT_URL): " $ZEIT_DEPLOYMENT_URL
+          echo "ZEIT_DEPLOYMENT_URL=$ZEIT_DEPLOYMENT_URL" >> $GITHUB_ENV
 
       # Run the E2E tests against the new Zeit deployment
       - name: Run E2E tests (Cypress)
@@ -280,8 +288,9 @@ jobs:
           # Parse the deployments (as json) to find the latest deployment url, while stripping the double quotes
           # TODO Do not use '.deployments [0].url' blindly, but filter the deployments array first to make sure to consider only the deployments where "name" is equal to $VERCEL_PROJECT_NAME
           ZEIT_DEPLOYMENT=`echo $ALL_ZEIT_DEPLOYMENTS | jq '.deployments [0].url' | tr -d \"`
-          echo "ZEIT_DEPLOYMENT_URL=https://$ZEIT_DEPLOYMENT" >> $GITHUB_ENV
+          ZEIT_DEPLOYMENT_URL="https://$ZEIT_DEPLOYMENT"
           echo "Url where to run LightHouse tests (ZEIT_DEPLOYMENT_URL): " $ZEIT_DEPLOYMENT_URL
+          echo "ZEIT_DEPLOYMENT_URL=$ZEIT_DEPLOYMENT_URL" >> $GITHUB_ENV
         env:
           ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }} # Passing github's secret to the worker
       # In order to store reports and then upload it, we need to create the folder before any tests
