Auto alias custom aliases when deploying

diff --git a/.github/workflows/deploy-zeit-staging.yml b/.github/workflows/deploy-zeit-staging.yml
--- a/.github/workflows/deploy-zeit-staging.yml
+++ b/.github/workflows/deploy-zeit-staging.yml
@@ -106,6 +106,32 @@ jobs:
           ZEIT_ALIASING_OUTPUT=`npx now alias $ZEIT_DEPLOYMENT_URL $ZEIT_DEPLOYMENT_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed, but the build will continue regardless."`
           echo $ZEIT_ALIASING_OUTPUT
           # TODO Resolve whether the aliasing has worked and change the GitHub comment "Comment PR (Deployment success)"
+
+          # Apply all aliases specified in the now.json file (if any is specified)
+          # Find all aliases configured in the customer deployment configuration file (now.json)
+          ZEIT_DEPLOYMENT_ALIASES_JSON=$(cat now.$CUSTOMER_REF_TO_DEPLOY.staging.json | jq --raw-output '.alias')
+          echo "Custom aliases: " $ZEIT_DEPLOYMENT_ALIASES_JSON
+
+          # Convert the JSON array into a bash array - See https://unix.stackexchange.com/a/615717/60329
+          readarray -t ZEIT_DEPLOYMENT_ALIASES < <(jq --raw-output '.alias[]' < now.$CUSTOMER_REF_TO_DEPLOY.staging.json)
+
+          # Check if there are no aliases configured (it will return "null" in such case, which is not the same as bash "empty")
+          if [ "$ZEIT_DEPLOYMENT_ALIASES" != null ] || [ ${#ZEIT_DEPLOYMENT_ALIASES[@]} > 0 ]
+          then
+            ZEIT_DEPLOYMENT_ALIASES_COUNT=${#ZEIT_DEPLOYMENT_ALIASES[@]}
+            echo "$ZEIT_DEPLOYMENT_ALIASES_COUNT alias(es) found. Aliasing them now..."
+
+            # For each alias configured, then assign it to the deployed domain
+            for DEPLOYMENT_ALIAS in "${ZEIT_DEPLOYMENT_ALIASES[@]}"; do
+              echo "npx now alias "$ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS
+              npx now alias $ZEIT_DEPLOYMENT_URL $DEPLOYMENT_ALIAS --token $ZEIT_TOKEN || echo "Aliasing failed for '$DEPLOYMENT_ALIAS', but the build will continue regardless."
+            done
+          else
+            # $ZEIT_DEPLOYMENT_ALIASES is null, this happens when it was not defined in the now.json file
+            echo "There are no more aliases to configure. You can add more aliases from your now.json 'alias' property. See https://vercel.com/docs/configuration?query=alias%20domain#project/alias"
+            echo "$ZEIT_DEPLOYMENT_ALIASES"
+          fi
+
         env:
           ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }} # Passing github's secret to the worker
           CURRENT_BRANCH: ${{ github.ref }} # Passing current branch to the worker
